CREATE DATABASE db_estoque;
CREATE DATABASE db_faturamento;

CREATE USER apiuser WITH PASSWORD 'R4mT8!ZqP2vL9@xK7hN3Wc';

\c db_estoque;
GRANT CONNECT ON DATABASE db_estoque TO apiuser;
GRANT USAGE ON SCHEMA public TO apiuser;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO apiuser;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO apiuser;
-- Garante permissões em tabelas que serão criadas futuramente
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO apiuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO apiuser;

\c db_faturamento;
GRANT CONNECT ON DATABASE db_faturamento TO apiuser;
GRANT USAGE ON SCHEMA public TO apiuser;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO apiuser;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO apiuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO apiuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO apiuser;